#   _    _                      _               _      
#  | |  | |                    | |             | |     
#  | |__| |_   _ _ __  _ __ ___| |__   __ _  __| | ___ 
#  |  __  | | | | '_ \| '__/ __| '_ \ / _` |/ _` |/ _ \
#  | |  | | |_| | |_) | |  \__ \ | | | (_| | (_| |  __/
#  |_|  |_|\__, | .__/|_|  |___/_| |_|\__,_|\__,_|\___|
#           __/ | |                                    
#          |___/|_|

# See https://github.com/loqusion/hyprshade#usage for usage...

[[shades]]
name = "redshift"
default = true  # shader to use during times when there is no other shader scheduled

